INSERT INTO quiz_categories (id, title, description, sort_order) VALUES
  ('mixed', 'Quick mix', 'A little science, geography, and history in one round.', 0),
  ('science', 'Science', 'Discoveries, nature, and the universe.', 1),
  ('geography', 'Geography', 'Places, landscapes, and our changing planet.', 2),
  ('history', 'History', 'People and moments that shaped the world.', 3),
  ('club_carnival', 'Club Carnival', 'Join the fun! Club Carnival is on October 16 at lunch. Help us make it amazing!', 4)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order;

INSERT INTO quiz_questions (category_id, difficulty, prompt, options, correct_index, explanation) VALUES
  ('science', 'easy', 'Which planet is the largest in our solar system?', '["Jupiter", "Saturn", "Earth", "Neptune"]'::jsonb, 0, 'Jupiter is more massive than all the other planets combined.'),
  ('science', 'easy', 'Which gas do plants absorb from the air during photosynthesis?', '["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"]'::jsonb, 1, 'Plants use carbon dioxide, water, and light to make sugars.'),
  ('science', 'easy', 'What is the chemical formula for water?', '["CO2", "O2", "H2O", "NaCl"]'::jsonb, 2, 'Each water molecule contains two hydrogen atoms and one oxygen atom.'),
  ('science', 'easy', 'Which organ pumps blood around the human body?', '["Lungs", "Liver", "Kidneys", "Heart"]'::jsonb, 3, 'The heart circulates blood through the body.'),
  ('science', 'easy', 'At sea level, water boils at what temperature in Celsius?', '["100", "80", "50", "120"]'::jsonb, 0, 'Water boils at 100 degrees Celsius at standard atmospheric pressure.'),
  ('science', 'medium', 'What is the closest star to Earth?', '["Proxima Centauri", "The Sun", "Sirius", "Vega"]'::jsonb, 1, 'The Sun is our nearest star, about 150 million kilometers away.'),
  ('science', 'medium', 'What shape does DNA most commonly take?', '["Single ring", "Flat sheet", "Double helix", "Triple spiral"]'::jsonb, 2, 'DNA is formed from two strands twisted into a double helix.'),
  ('science', 'medium', 'What is the chemical symbol for gold?', '["Ag", "Gd", "Go", "Au"]'::jsonb, 3, 'Au comes from the Latin name for gold, aurum.'),
  ('science', 'medium', 'What is the SI unit of force?', '["Newton", "Joule", "Watt", "Pascal"]'::jsonb, 0, 'One newton is the force needed to accelerate one kilogram by one meter per second squared.'),
  ('science', 'medium', 'What pH value is neutral at room temperature?', '["0", "7", "10", "14"]'::jsonb, 1, 'A pH of 7 is neutral; lower values are acidic and higher values are basic.'),
  ('science', 'hard', 'Which cell structure produces most of the usable energy in a human cell?', '["Ribosome", "Nucleus", "Mitochondrion", "Golgi apparatus"]'::jsonb, 2, 'Mitochondria convert energy from food into ATP the cell can use.'),
  ('science', 'hard', 'Which theory did Albert Einstein publish in 1905?', '["Plate tectonics", "Germ theory", "Quantum field theory", "Special relativity"]'::jsonb, 3, 'Einstein published his special theory of relativity in 1905.'),
  ('science', 'hard', 'What is the atomic number of uranium?', '["92", "88", "94", "82"]'::jsonb, 0, 'Uranium has 92 protons in its nucleus.'),
  ('science', 'hard', 'Approximately how fast does light travel through a vacuum?', '["30,000 km/s", "300,000 km/s", "3,000 km/s", "3,000,000 km/s"]'::jsonb, 1, 'Light travels at about 299,792 kilometers per second in a vacuum.'),
  ('science', 'hard', 'Which particle is associated with the mechanism that gives many fundamental particles mass?', '["Photon", "Neutrino", "Higgs boson", "Gluon"]'::jsonb, 2, 'The Higgs boson is associated with the Higgs field and the origin of mass for many particles.'),
  ('geography', 'easy', 'What is the capital of Japan?', '["Osaka", "Kyoto", "Sapporo", "Tokyo"]'::jsonb, 3, 'Tokyo is the capital and most populous city of Japan.'),
  ('geography', 'easy', 'The Nile River flows through which continent?', '["Africa", "Asia", "South America", "Europe"]'::jsonb, 0, 'The Nile flows north through northeastern Africa.'),
  ('geography', 'easy', 'What is the largest ocean on Earth?', '["Atlantic", "Pacific", "Indian", "Arctic"]'::jsonb, 1, 'The Pacific Ocean is the largest and deepest ocean.'),
  ('geography', 'easy', 'Which river is closely associated with ancient Egyptian civilization?', '["Amazon", "Danube", "Nile", "Yangtze"]'::jsonb, 2, 'The Nile provided water and fertile land for ancient Egypt.'),
  ('geography', 'easy', 'Which continent is also a country?', '["Europe", "Antarctica", "South America", "Australia"]'::jsonb, 3, 'Australia is both a country and the smallest continent.'),
  ('geography', 'medium', 'The Andes mountain range runs along the western edge of which continent?', '["South America", "Africa", "Asia", "Europe"]'::jsonb, 0, 'The Andes stretch along the western side of South America.'),
  ('geography', 'medium', 'Which country is crossed by the equator and is named after it?', '["Kenya", "Ecuador", "Indonesia", "Brazil"]'::jsonb, 1, 'Ecuador takes its name from the equator, which crosses the country.'),
  ('geography', 'medium', 'What is the capital of Canada?', '["Toronto", "Vancouver", "Ottawa", "Montreal"]'::jsonb, 2, 'Ottawa is the capital of Canada, in the province of Ontario.'),
  ('geography', 'medium', 'Lake Baikal, the world deepest freshwater lake, is in which country?', '["Mongolia", "China", "Kazakhstan", "Russia"]'::jsonb, 3, 'Lake Baikal lies in southern Siberia, Russia.'),
  ('geography', 'medium', 'The Sahara Desert is located on which continent?', '["Africa", "Asia", "Australia", "North America"]'::jsonb, 0, 'The Sahara spans much of northern Africa.'),
  ('geography', 'hard', 'What is the capital of Cyprus?', '["Valletta", "Nicosia", "Limassol", "Athens"]'::jsonb, 1, 'Nicosia is the capital of Cyprus and is divided between its Greek and Turkish Cypriot communities.'),
  ('geography', 'hard', 'Which country is completely surrounded by South Africa?', '["Eswatini", "Botswana", "Lesotho", "Namibia"]'::jsonb, 2, 'Lesotho is an independent country entirely enclosed by South Africa.'),
  ('geography', 'hard', 'Which strait separates Alaska from Russia?', '["Davis Strait", "Gibraltar Strait", "Drake Passage", "Bering Strait"]'::jsonb, 3, 'The Bering Strait separates the Chukchi Peninsula from Alaska.'),
  ('geography', 'hard', 'What is the largest inland body of water on Earth?', '["Caspian Sea", "Lake Superior", "Lake Victoria", "Aral Sea"]'::jsonb, 0, 'The Caspian Sea is the world largest enclosed inland body of water.'),
  ('geography', 'hard', 'Mount Kilimanjaro is in which country?', '["Kenya", "Tanzania", "Uganda", "Ethiopia"]'::jsonb, 1, 'Kilimanjaro is in northeastern Tanzania, near the Kenyan border.'),
  ('history', 'easy', 'Who was the first president of the United States?', '["Thomas Jefferson", "John Adams", "George Washington", "James Madison"]'::jsonb, 2, 'George Washington served as the first US president from 1789 to 1797.'),
  ('history', 'easy', 'The pyramids at Giza were built by which ancient civilization?', '["Roman", "Greek", "Mayan", "Egyptian"]'::jsonb, 3, 'The Giza pyramids were built in ancient Egypt during the Old Kingdom.'),
  ('history', 'easy', 'In what year did World War II end?', '["1945", "1939", "1942", "1950"]'::jsonb, 0, 'World War II ended in 1945, following the surrender of Germany and Japan.'),
  ('history', 'easy', 'Which 1215 document limited the power of the English king?', '["The Bill of Rights", "Magna Carta", "The Domesday Book", "The Mayflower Compact"]'::jsonb, 1, 'Magna Carta established that the English king was subject to the law.'),
  ('history', 'easy', 'In which city is the Colosseum?', '["Athens", "Istanbul", "Rome", "Cairo"]'::jsonb, 2, 'The Colosseum is an ancient Roman amphitheater in the center of Rome.'),
  ('history', 'medium', 'Which city fell to the Ottoman Empire in 1453?', '["Rome", "Alexandria", "Jerusalem", "Constantinople"]'::jsonb, 3, 'Constantinople fell to Ottoman forces in 1453 and later became Istanbul.'),
  ('history', 'medium', 'The Renaissance began in which present-day country?', '["Italy", "France", "Spain", "Germany"]'::jsonb, 0, 'The Renaissance began in Italy, with early centers including Florence.'),
  ('history', 'medium', 'What was the Silk Road primarily known for?', '["A military wall", "Trade routes linking Asia and Europe", "A pilgrimage trail", "A sea passage"]'::jsonb, 1, 'The Silk Road was a network of trade routes connecting regions across Eurasia.'),
  ('history', 'medium', 'In what year did humans first land on the Moon?', '["1959", "1965", "1969", "1972"]'::jsonb, 2, 'Apollo 11 landed on the Moon in July 1969.'),
  ('history', 'medium', 'In what year was the United States Declaration of Independence adopted?', '["1783", "1812", "1492", "1776"]'::jsonb, 3, 'The Continental Congress adopted the Declaration on July 4, 1776.'),
  ('history', 'hard', 'The Peace of Westphalia, which ended the Thirty Years War, was signed in what year?', '["1648", "1618", "1688", "1715"]'::jsonb, 0, 'The Peace of Westphalia was signed in 1648.'),
  ('history', 'hard', 'In what year did the Haitian Revolution begin?', '["1804", "1791", "1776", "1815"]'::jsonb, 1, 'The Haitian Revolution began in 1791 and led to independence in 1804.'),
  ('history', 'hard', 'Who is most closely associated with introducing movable-type printing in Europe?', '["Leonardo da Vinci", "Marco Polo", "Johannes Gutenberg", "Nicolaus Copernicus"]'::jsonb, 2, 'Johannes Gutenberg developed a movable-type printing system in Europe in the 15th century.'),
  ('history', 'hard', 'What was the capital of the Byzantine Empire for most of its history?', '["Athens", "Antioch", "Alexandria", "Constantinople"]'::jsonb, 3, 'Constantinople served as the Byzantine Empire capital until its fall in 1453.'),
  ('history', 'hard', 'In what year did the Meiji Restoration begin in Japan?', '["1868", "1853", "1889", "1905"]'::jsonb, 0, 'The Meiji Restoration began in 1868, restoring imperial rule and launching rapid modernization.'),
  ('club_carnival', 'easy', 'Will you be participating and helping our club in Club Carnival?', '["Yes, I want to help!", "No, I cannot help", "Maybe later", "I will think about it"]'::jsonb, 0, 'Great! We need enthusiastic helpers to make Club Carnival a success!'),
  ('club_carnival', 'easy', 'What do you want to help us with?', '["Putting food in plates", "Money handling (must be good at math)", "Asking people for what they want (communicator and leader)", "Going around and getting friends to come buy"]'::jsonb, 0, 'Every role is important! Let us know your preference.'),
  ('club_carnival', 'easy', 'Do you want to bring something for our club to sell?', '["Yes, I have something in mind!", "No, I will not bring anything", "Maybe, let me think", "I will ask my friends"]'::jsonb, 0, 'Awesome! Homemade treats and unique items are always welcome!'),
  ('club_carnival', 'easy', 'What date is Club Carnival?', '["October 15", "October 16 at lunch", "October 17", "October 18"]'::jsonb, 1, 'Mark your calendar! Club Carnival is on October 16 at lunch. See you there!'),
  ('club_carnival', 'easy', 'How can you help more people find our Club Carnival booth?', '["Invite friends to stop by", "Keep the booth a secret", "Tell people the event is canceled", "Ask people to avoid the booth"]'::jsonb, 0, 'Inviting friends and classmates helps bring more visitors to the club booth.')
ON CONFLICT (category_id, difficulty, prompt) DO NOTHING;
